/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GestionFormules.java
 *
 * Created on 14 févr. 2014, 11:58:48
 */
package deal.esprit.gui;

import deal.esprit.dao.StatistiqueDao;
import deal.esprit.entities.Statistique;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author Jihed
 */
public class GenererStatistiques extends javax.swing.JFrame {

    /**
     * Creates new form MenuGestionDepot
     */
    public GenererStatistiques() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        canvas1 = new java.awt.Canvas();
        client_prestataire_statistique = new javax.swing.JButton();
        dealCategorie = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        client_prestataire_statistique.setText("Client/prestataire");
        client_prestataire_statistique.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client_prestataire_statistiqueActionPerformed(evt);
            }
        });

        dealCategorie.setText("Produit/Categorie");
        dealCategorie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dealCategorieActionPerformed(evt);
            }
        });

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dealCategorie)
                    .addComponent(client_prestataire_statistique))
                .addContainerGap(877, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(client_prestataire_statistique)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(dealCategorie)))
                .addContainerGap(615, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void client_prestataire_statistiqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_client_prestataire_statistiqueActionPerformed
        // TODO add your handling code here:

        Statistique stat = new Statistique();

        StatistiqueDao GetNombre = new StatistiqueDao();

        DefaultPieDataset pieDataset = new DefaultPieDataset(); //Dataset qui va contenir les Données 
        //remplissage du  dataset du pie
        pieDataset = stat.clientPrestataire();
        // Creation du fromage 
        JFreeChart chart = chart = ChartFactory.createPieChart3D("Client/prestataire", pieDataset, true, true, false);            //Graphe
        //affichage
        ChartFrame frame = new ChartFrame("Client/prestataire", chart);
        frame.setSize(500, 500);
        frame.setVisible(true);


    }//GEN-LAST:event_client_prestataire_statistiqueActionPerformed

    private void dealCategorieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dealCategorieActionPerformed
        // TODO add your handling code here:
        Statistique stat = new Statistique();

        StatistiqueDao GetNombre = new StatistiqueDao();
        //Dataset qui va contenir les Données 
        DefaultPieDataset pieDataset = new DefaultPieDataset();
        //remplissage du  dataset du pie
        pieDataset = stat.dealcategorie();
        // Creation du fromage 
        JFreeChart chart = chart = ChartFactory.createPieChart3D("Client/prestataire", pieDataset, true, true, false);            //Graphe
        //affichage
        ChartFrame frame = new ChartFrame("Client/prestataire", chart);
        frame.setSize(500, 500);
        frame.setVisible(true);
    }//GEN-LAST:event_dealCategorieActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new GenererStatistiques().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Canvas canvas1;
    private javax.swing.JButton client_prestataire_statistique;
    public javax.swing.JButton dealCategorie;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables

}
